Year = 2022
Weekday = 1

Sections = [
    "dailies"
]

# Layout-related stuff
[Document.Screen]
Width = 156
Height = 230

[Document.Margin]
Top = 10
Bottom = 10
Left = 14
Right = 5

[Document.MarginNotes]
Separator = 4
Width = 10
Reverse = true

[Document.Debug]
ShowLinks = false
ShowFrames = false

### planner setup
[MOSHeaderParameters]
AfterHeaderSkip = 2.5

# daily setup
[DailyParameters]
ScheduleColumnWidth = 52
PrioritiesAndNotesColumnWidth = 80
ColumnsSeparatorWidth = 5
PrioritiesAndNotesSkip = 7
ScheduleToTheRight = true
EnableLittleCalendar = true

[DailyParameters.ScheduleParameters]
FromHour = 7
ToHour = 19
Format = "15"
LineHeight = 5

[DailyParameters.TodosParameters]
Number = 8
LineHeight = 5

[DailyParameters.NotesParameters]
[DailyParameters.NotesParameters.Dotted]
Distance = 5
Rows = 27
Columns = 17

[DailyParameters.LittleCalendarParameters]
WeekNumberToTheRight = true
