Year = 2022
Weekday = 1

Sections = [
#    "dailies",
#    "daily_notes",
#    "daily_reflect",
    "notes"
]

# Layout-related stuff
[Document.Screen]
Width = 156
Height = 230

[Document.Margin]
Top = 10
Bottom = 10
Left = 14
Right = 5

[Document.MarginNotes]
Separator = 6.3
Width = 10
Reverse = true

[Document.Debug]
ShowLinks = false
ShowFrames = false

### planner setup
[MOSHeaderParameters]
AfterHeaderSkip = 2.5
MonthAndQuarterSpace = 11.7
[MOSHeaderParameters.HeadingTabLineParameters]
VerticalSpacing = 1
SpaceBetweenColumns = 2
[MOSHeaderParameters.QuartersTabLineParameters]
VerticalSpacing = 2
SpaceBetweenColumns = 5
[MOSHeaderParameters.MonthsTabLineParameters]
VerticalSpacing = 2
SpaceBetweenColumns = 3.5

# daily setup
[DailyParameters]
ScheduleColumnWidth = 52
PrioritiesAndNotesColumnWidth = 80
ColumnsSeparatorWidth = 5
PrioritiesAndNotesSkip = 7
ScheduleToTheRight = true
EnableLittleCalendar = true

[DailyParameters.ScheduleParameters]
FromHour = 7
ToHour = 19
Format = "15"
LineHeight = 5

[DailyParameters.TodosParameters]
Number = 8
LineHeight = 5

[DailyParameters.NotesParameters]
[DailyParameters.NotesParameters.Lined]
Number = 27
Height = 5

[DailyParameters.LittleCalendarParameters]
WeekNumberToTheRight = true
WeekHighlight = true

# daily notes setup
[DailyNotesParameters]
Pages = 1
[DailyNotesParameters.NotesParameters.Lined]
Number = 33
Height = 5

# daily reflect setup
[DailyReflectParameters]
BlocksSeparateSize = 5
[DailyReflectParameters.GoalsNotesParameters.Lined]
Number = 3
Height = 5
[DailyReflectParameters.GratefulNotesParameters.Lined]
Number = 5
Height = 5
[DailyReflectParameters.BestThingNotesParameters.Lined]
Number = 5
Height = 5
[DailyReflectParameters.DailyLogNotesParameters.Lined]
Number = 20
Height = 5

# notes setup
[NotesParameters]
[NotesParameters.IndexParameters]
ItemsPerPage = 10
Pages = 3
[NotesParameters.NotesParameters.Lined]
Number = 33
Height = 5
