Year = 2022
Weekday = 1

Sections = [
    "quarterlies",
#    "monthlies",
#    "weeklies",
#    "dailies",
#    "daily_notes",
#    "daily_reflect",
#    "notes",
#    "todo",
]

# Layout-related stuff
[Document.Screen]
Width = 156
Height = 230

[Document.Margin]
Top = 10
Bottom = 5
Left = 14
Right = 5

[Document.MarginNotes]
Separator = 6.3
Width = 10
Reverse = true

[Document.Debug]
ShowLinks = true
ShowFrames = false

### planner setup
[MOSHeaderParameters]
AfterHeaderSkip = 2.5
MonthAndQuarterSpace = 11.7
[MOSHeaderParameters.HeadingTabLineParameters]
VerticalSpacing = 1.5
SpaceBetweenColumns = 2
[MOSHeaderParameters.QuartersTabLineParameters]
VerticalSpacing = 2
SpaceBetweenColumns = 5
[MOSHeaderParameters.MonthsTabLineParameters]
VerticalSpacing = 2
SpaceBetweenColumns = 3.5

[QuarterlyParameters]
[QuarterlyParameters.NotesParameters.Dotted]
Distance = 5
Columns = 17
Rows = 33

[MonthlyParameters]
[MonthlyParameters.FullPageCalendarParameters]
WeekNumberToTheRight = true

[WeeklyParameters]
LeftColumnWidth = 40
CenterColumnWidth = 45
RightColumnWidth = 40
TwoColumnWidth = 90
Separator = 5

[WeeklyParameters.LeftColumnParameters.Dotted]
Distance = 5
Columns = 9
Rows = 12

[WeeklyParameters.CenterColumnParameters.Dotted]
Distance = 5
Columns = 10
Rows = 12

[WeeklyParameters.RightColumnParameters.Dotted]
Distance = 5
Columns = 9
Rows = 12

[WeeklyParameters.TwoColumnParameters.Dotted]
Distance = 5
Columns = 19
Rows = 12

# daily setup
[DailyParameters]
ScheduleColumnWidth = 52
PrioritiesAndNotesColumnWidth = 80
ColumnsSeparatorWidth = 5
PrioritiesAndNotesSkip = 7
ScheduleToTheRight = true
EnableLittleCalendar = true

[DailyParameters.ScheduleParameters]
FromHour = 7
ToHour = 19
Format = "15"
LineHeight = 5

[DailyParameters.TodosParameters]
Number = 8
LineHeight = 5

[DailyParameters.NotesParameters]
[DailyParameters.NotesParameters.Lined]
Number = 27
Height = 5

[DailyParameters.LittleCalendarParameters]
WeekNumberToTheRight = true
WeekHighlight = true
DayHighlight = true

# daily notes setup
[DailyNotesParameters]
Pages = 1
[DailyNotesParameters.NotesParameters.Lined]
Number = 33
Height = 5

# daily reflect setup
[DailyReflectParameters]
BlocksSeparateSize = 5
[DailyReflectParameters.GoalsNotesParameters.Lined]
Number = 3
Height = 5
[DailyReflectParameters.GratefulNotesParameters.Lined]
Number = 5
Height = 5
[DailyReflectParameters.BestThingNotesParameters.Lined]
Number = 5
Height = 5
[DailyReflectParameters.DailyLogNotesParameters.Lined]
Number = 20
Height = 5

# notes setup
[NotesParameters]
[NotesParameters.IndexParameters]
ItemsPerPage = 25
Pages = 4
LineHeight = 8
[NotesParameters.NotesParameters.Lined]
Number = 33
Height = 5

[TodosParameters]
[TodosParameters.IndexParameters]
ItemsPerPage = 25
Pages = 4
LineHeight = 8
[TodosParameters.TodosParameters]
Number = 33
LineHeight = 6
