Year = 2022
Weekday = 0

EnabledSections = [
    "title",
    "dailies"
]

# Layout-related stuff
[Document.Screen]
Width = 156
Height = 230

[Document.Margin]
Top = 10
Bottom = 10
Left = 5
Right = 5

[Document.MarginNotes]
Separator = 2
Width = 8
Reverse = true

[Document.Debug]
ShowLinks = false
ShowFrames = false
